name: Run tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # - name: Install libvips
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libvips-dev libglib2.0-dev

      - name: Check out Git repository
        uses: actions/checkout@v2.3.4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          check-latest: true

      # force sharp rebuild
      # - run: yarn remove sharp
      # - run: yarn add --arch=x64 --platform=linux sharp
      # - run: yarn rebuild --arch=x64 --platform=linux sharp
      # - run: yarn install
      - run: npm install
      - run: npm run test
