name: Run tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install libvips
        run: sudo apt-get install -y libvips-dev

      - name: Check out Git repository
        uses: actions/checkout@v2.3.4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          check-latest: true

      - run: yarn install
      - run: yarn run test
